name: drklepson_future_loading
description: With this extension, you can create a loading dialog that lasts from the moment you run the Future functions until the process is complete.
version: 0.0.2
homepage: https://github.com/drklepson/drklepson_future_loading

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=3.3.6'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

